foreground         #c2c5c6
background         #0c171e
background_opacity 1.0
cursor             #c2c5c6

active_tab_foreground     #0c171e
active_tab_background     #c2c5c6
inactive_tab_foreground   #c2c5c6
inactive_tab_background   #0c171e

active_border_color   #c2c5c6
inactive_border_color #0c171e
bell_border_color     #295168

color0       #0c171e
color8       #5c6970
color1       #295168
color9       #376C8B
color2       #335b74
color10      #447A9B
color3       #3d6982
color11      #528CAE
color4       #4b7288
color12      #6498B6
color5       #4d7f9c
color13      #67AAD1
color6       #5d91ab
color14      #7DC2E5
color7       #8f969a
color15      #c2c5c6
